### ISSUE TITLE
If fallbackRule is defined, it ignores the other rules

### ISSUE THREAD

**Issue by THPubs** [maticzav/graphql-shield#211] opened 2018-12-05 08:24 UTC
# Bug report

I just tried to set the `fallbackRule` to `deny`. The problem is, when this is set, even if the other rules pass, the server gives a **Not authorized** error.

1. This is my GraphQL Schema. 

```graphql
type Branch {
  id: ID!
  name: String
}

type Query {
  branch(where: BranchWhereUniqueInput!): Branch
  branches(
    where: BranchWhereInput
    orderBy: BranchOrderByInput
    skip: Int
    after: String
    before: String
    first: Int
    last: Int
  ): [Branch]!
}
```

2. This is the invoked query

```graphql
query {
  restaurant(where: { id: "_" }) {
    id
  }
}

```

3. I use these permissions

```js
const isAuthenticated = rule({ cache: 'no_cache' })(async (parent, args, ctx) => {
  console.log(ctx.user);
  return ctx.user !== null;
});

const permissions = shield(
  {
    Query: {
      branches: isAuthenticated,
      branch: isAuthenticated,
    },
  },
  {
    fallbackRule: allow,
    graphiql: true
  }
);
```

4. This is the error I see

```js
Error: Not Authorised!
```

## Expected behaviour

The user is coming to the `isAuthenticated` method. But if `fallbackRule` is defined, the `isAuthenticated` method runs and the user gets console logged. But it still returns `Error: Not Authorised!`. If I remove `fallbackRule` or set it to `allow`, the query runs without issue and also blocks if the user is actually not there.

## Actual behaviour

The `fallbackRule` should be executed only if there are no rules set for the query.

**Comment by caioflores** [comment] 2018-12-13 15:56
I'm having the same problem here, maybe it's a cache problem?

**Comment by THPubs** [comment] 2018-12-13 15:59
> Hmm @THPubs, that's quite unusual! Would you mind creating a simple reproduction repository or CodeSandbox? This way I can help you with the issue a lot more quickly 🙂

Really sorry in a tight schedule. Not sure whether I can create a sample repo soon 😢

**Comment by maticzav** [comment] 2018-12-14 10:11
Hey @THPubs 👋,

I just noticed; the schema you provided in the issue report doesn't match the executed query. Could you sync that? I believe the issue stems from the schema definition, in particular, `nullable` and `non-nullable` fields. You can read more about it here;

https://github.com/maticzav/graphql-shield/issues/97#issuecomment-404867307

**Comment by ph55** [comment] 2018-12-31 11:32
Same issue here. 
Why not investigated ? Many users confirmed.

My example:
```ts
shield({
  Mutation: {
    login: rule()(async () => true);
  }
}, {
  fallbackRule: deny
  fallbackError: new ForbiddenError('Access denied')
})
```

`login` return 'Access denied'

**Comment by ph55** [comment] 2018-12-31 11:44
Make sure response type also allowed.

Example:
```gql
type Mutation {
  login(input: LoginInput!): LoginResponse
}
```

Not enough for login whitelist:
```ts
shield({ Mutation: { login: allow } }, { fallbackRule: deny })
```

Should be:
```ts
shield({ Mutation: { login: allow }, LoginResponse: allow }, { fallbackRule: deny })
```

Maybe worth to mention in docs.

**Comment by ph55** [comment] 2019-01-07 17:54
Or maybe `fallbackRule` could be set per type.
For example:
```ts
// ...
{ 
  fallbackRules: {
    Query: deny,
    Mutation: deny,
    Resource: allow,
    Field: allow
  } 
}
```

**Comment by maticzav** [comment] 2019-01-07 21:33
@ellipticaldoor I believe this is not a good practice because multiple fields could point to the same type. Trying to guess permissions would therefore usually resolve in a mess.

@ph55 I believe there's no real benefit of having such grained support for `fallbackRule`. I think this is an anti-pattern seemingly useful in small-scale projects, however, becomes rather tedious to maintain on large repositories with over dozen types because it posses a thread of split permission definitions which reduce code legibility.

**Comment by ph55** [comment] 2019-01-09 17:24
@maticzav 
It was just attempt to solve following behaviour https://github.com/maticzav/graphql-shield/issues/211#issuecomment-450636577 for `{ fallbackRule: deny }`

If you allow `Query` or `Mutation` common sense tells that returned type should be allowed as well.
Unless you want to deny some of returned fields.

But I've already found the way to define such behaviour with custom `fallbackRule`.
So in some way - it's already supported. https://github.com/maticzav/graphql-shield/issues/243#issuecomment-452771010

**Comment by maticzav** [comment] 2019-01-10 06:52
@ph55 I love your suggestion on #243! What I tried to portray in my comment below is the following situation;

```graphql
type Query {
  viewer: Viewer
  houses: [House!]!
}

type Viewer {
  houses: [House!]!
}

type House {
  id: ID!
  name: String!
  price: Float!
  ...
  inquiries: [String!]!
}
```

Now, imagine everything is public, except `inquiries` which only owners of the house can access. When having one unambiguous relation to a type, I indeed agree that such functionality could be beneficial, however, when multiple fields point to one, it's not that trivial anymore.

```ts
const permissions = shield({
  Query: {
    viewer: isAuthenticated,
    houses: allow,
  },
  House: {
    id: allow,
    name: allow,
    price: allow,
    ...
    inquiries: isHouseOwner,
})
```

I am guessing how we could magically yet intuitively predict permission type in the current system. Perhaps you have an idea? 🙂

**Comment by maticzav** [comment] 2019-01-10 06:53
I will close the issue now because we've drifted far from the original question. I encourage you, however, to continue the discussion of the options in the thread, or even better open up a new one, summing our current findings, and let's keep the conversation going there 🙂

**Closed by maticzav** 2019-01-10 06:53 UTC

**Comment by lackovic** [comment] 2019-02-26 15:12
I had the same problem and resolved allowing the response type as well, thanks @ph55 

If I think about it now it makes sense, but it's not that straightforward. I am not sure I would have come to this conclusion all by myself.

I think it would be helpful if this would be clarified in the documentation.

**Comment by maticzav** [comment] 2019-02-26 20:14
#300
