### ISSUE TITLE
Problems work with the renamed field

### ISSUE THREAD

**Issue by baby1990** [maticzav/graphql-shield#244] opened 2019-01-08 12:44 UTC
When I add rules to a relation field such as messages, sometimes I may be want to get the messages NOT_READ or READ in one query. Just like this:
```
query {
  me {
    id
    messagesNotRead: messages(where: {status: NOT_READ}, orderBy: createdAt_DESC) {
        id
        status
    }
    messages(where: {status: READ}, orderBy: createdAt_DESC) {
        id
        status
    }
  }
}
```
But after use this middleware, add some rules(like isAuthenticated) to the ``messages`` field of type ``User``, the result of the query above is not worked correctly. The renamed field ``messagesNotRead``
cannot work through the validation of the ``messages`` field.
The value of ``messagesNotRead`` field is just the same of ``messages`` above:
```
{
  "data": {
    "me": {
      "id": "cjn105vxk00110759vg8eq8gz",
      "messagesNotRead": [
        {
          "id": "cjoy6mxbm011k0759uaito9hs",
          "status": "READ"
        },
        {
          "id": "cjoy3qcsj010807595jbtqt35",
          "status": "READ"
        },
      ],
      "messages": [
        {
          "id": "cjoy6mxbm011k0759uaito9hs",
          "status": "READ"
        },
        {
          "id": "cjoy3qcsj010807595jbtqt35",
          "status": "READ"
        },
        ]
    }
  }
}
```
when just rename the ``messages`` without an additional ``messages`` field，the renamed field just return null, not []:
```
query {
  me {
    id
    messagesNotRead: messages(where: {status: NOT_READ}, orderBy: createdAt_DESC) {
        id
      	status
    }
  }
}
```
```
{
  "data": {
    "me": {
      "id": "cjn105vxk00110759vg8eq8gz",
      "messagesNotRead": null
    }
  }
}
```
The expected result should like this:
```
query {
  me {
    id
    messages(where: {status: NOT_READ}, orderBy: createdAt_DESC) {
        id
      	status
    }
  }
}
```
```
{
  "data": {
    "me": {
      "id": "cjn105vxk00110759vg8eq8gz",
      "messages": []
    }
  }
}
```

**Comment by maticzav** [comment] 2019-01-09 12:08
Hey @baby1990 👋,

That's an interesting question! Could you provide a reproduction repository or CodeSandbox? This way I can curb the issue a lot more quickly. 🙂

**Comment by baby1990** [comment] 2019-01-10 03:18
> Hey @baby1990 👋,
> 
> That's an interesting question! Could you provide a reproduction repository or CodeSandbox? This way I can curb the issue a lot more quickly. 🙂

I try to use graphql-yoga and graphql-shield to perform a simple demo for this situation. But the demo works correctly. 

The problems above accurs when I use graphql-prisma / graphql-yoga / graphql-shield to perform a backend service. I wonder it maybe a problem of graphql-prisma.

**Comment by maticzav** [comment] 2019-01-10 07:14
@baby1990, let me know if you find any further information. Maybe this could be connected to field alias, could you try that as well?

Regardless, I think it would be super useful if we could have a common ground with a reproduction example. Let me know if you could compose that. 🙂

**Comment by baby1990** [comment] 2019-01-16 09:06
> @baby1990, let me know if you find any further information. Maybe this could be connected to field alias, could you try that as well?
> 
> Regardless, I think it would be super useful if we could have a common ground with a reproduction example. Let me know if you could compose that. 🙂

I try to update my prisma service to 1.24(latest version)，and the problems not resolved.

**Comment by baby1990** [comment] 2019-01-21 00:50
> @baby1990, let me know if you find any further information. Maybe this could be connected to field alias, could you try that as well?
> 
> Regardless, I think it would be super useful if we could have a common ground with a reproduction example. Let me know if you could compose that. 🙂

Actually, I tried to use the custom directives to do the permission instead of graphql-shield. But the problems not resolved. So I don't think there is something wrong with graphql-shield.

**Comment by pantharshit00** [comment] 2019-01-23 15:24
https://github.com/prisma/prisma/issues/3881#issuecomment-456842794

@maticzav this is totally unrelated to graphql-shield I think you can close this here 🙂

**Comment by maticzav** [comment] 2019-01-23 15:25
Due to @pantharshit00's investigation, I'll close the issue. Feel free to reopen it if you feel this is still a relevant topic.

**Closed by maticzav** 2019-01-23 15:25 UTC
Labels: kind/question
